# Generated by Django 5.2.3 on 2025-07-20 14:57

import django.db.models.deletion
import django.utils.timezone
import folhadeponto.utilitarios.acoes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=191, unique=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=191, unique=True)),
                ('sigla', models.CharField(max_length=191, unique=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='logoscampi/', validators=[folhadeponto.utilitarios.acoes.validar_arquivo_imagens])),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Carreira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=191, unique=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=191)),
                ('data', models.DateField(max_length=191, unique=True)),
                ('tipo', models.CharField(max_length=191)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=191, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=30, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=191, unique=True)),
                ('nivel', models.CharField(max_length=191)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='folhadeponto.area')),
                ('carreira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='folhadeponto.carreira')),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=191)),
                ('matricula', models.CharField(max_length=191, unique=True)),
                ('situacao', models.BooleanField(default=True)),
                ('em_pgd', models.BooleanField(default=False)),
                ('data_exercicio', models.DateField()),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='folhadeponto.cargo')),
                ('funcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='folhadeponto.funcao')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=191, unique=True)),
                ('sigla', models.CharField(max_length=191, unique=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setores_que_coordena', to='folhadeponto.servidor')),
            ],
        ),
        migrations.AddField(
            model_name='servidor',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidores', to='folhadeponto.setor'),
        ),
        migrations.CreateModel(
            name='Folha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.CharField(max_length=50)),
                ('dados', models.TextField()),
                ('setor_mes_ano', models.CharField(editable=False, max_length=191, unique=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='folhadeponto.setor')),
            ],
        ),
    ]
