# Generated by Django 5.2.3 on 2025-07-20 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folhadeponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='folhadeponto.campus'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='folhadeponto.campus'),
        ),
        migrations.AddField(
            model_name='carreira',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='folhadeponto.campus'),
        ),
        migrations.AddField(
            model_name='data',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='folhadeponto.campus'),
        ),
        migrations.AddField(
            model_name='folha',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='folhadeponto.campus'),
        ),
        migrations.AddField(
            model_name='funcao',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='folhadeponto.campus'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='folhadeponto.campus'),
        ),
        migrations.AddField(
            model_name='setor',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='folhadeponto.campus'),
        ),
    ]
