# Generated by Django 5.2.3 on 2025-07-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folhadeponto', '0003_campus_email_campus_groups_campus_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='password',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='user_permissions',
        ),
    ]
