# Generated by Django 5.2.3 on 2025-07-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folhadeponto', '0005_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='email',
        ),
    ]
