# Generated by Django 5.2.3 on 2025-07-24 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folhadeponto', '0007_alter_cargo_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='folhadeponto.usuario'),
        ),
    ]
