# Generated by Django 5.2.3 on 2025-07-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folhadeponto', '0008_servidor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='abrangencia',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
