# Generated by Django 5.2.3 on 2025-07-25 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folhadeponto', '0009_data_abrangencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
