# Generated by Django 5.2.4 on 2025-08-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folhadeponto', '0010_usuario_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='data_fim_afastamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='data_inicio_afastamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='em_afastamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servidor',
            name='tipo',
            field=models.BooleanField(default=True),
        ),
    ]
