# Generated by Django 5.2.4 on 2025-08-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folhadeponto', '0011_servidor_data_fim_afastamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='tipo_afastamento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
