# Generated by Django 5.2.4 on 2025-08-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folhadeponto', '0012_servidor_tipo_afastamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='tipo',
            field=models.CharField(default='EFETIVO', max_length=191),
        ),
    ]
