# Generated by Django 5.2.4 on 2025-08-04 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folhadeponto', '0013_alter_servidor_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='substituto',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'CONTRATADO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='efetivo_substituido_por', to='folhadeponto.servidor'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='tipo',
            field=models.CharField(choices=[('EFETIVO', 'Efetivo'), ('CONTRATADO', 'Contratado')], default='EFETIVO', max_length=20),
        ),
    ]
