# Generated by Django 5.2.4 on 2025-08-05 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folhadeponto', '0014_servidor_substituto_alter_servidor_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='tipo',
            field=models.CharField(choices=[('EFETIVO', 'EFETIVO'), ('CONTRATADO', 'CONTRATADO')], default='EFETIVO', max_length=20),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_contrato', models.DateField()),
                ('data_fim_contrato', models.DateField()),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folhadeponto.servidor')),
            ],
        ),
    ]
