# Generated by Django 5.2.4 on 2025-08-05 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folhadeponto', '0015_alter_servidor_tipo_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='campus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='folhadeponto.campus'),
        ),
    ]
