# Generated by Django 5.2.4 on 2025-08-05 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folhadeponto', '0016_contrato_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='servidor',
            field=models.ForeignKey(limit_choices_to={'tipo': 'CONTRATADO'}, on_delete=django.db.models.deletion.CASCADE, to='folhadeponto.servidor', unique=True),
        ),
    ]
