# Generated by Django 5.2.4 on 2025-08-06 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folhadeponto', '0017_alter_contrato_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='substituto',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'CONTRATADO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='efetivo_substituido_por', to='folhadeponto.servidor', unique=True),
        ),
    ]
